### ISSUE TITLE
worker_create.sh does not work on OS X

### ISSUE THREAD

**Issue by keunwoo** [spatialos/CppBlankProject#5]
`worker_create.sh` uses `cp -rT` to copy the worker path to its destination. The `-T` flag is a GNU-ism that is not available in BSD-style `cp` (i.e. OS X). I posted a PR which fixes this on my machine:

https://github.com/spatialos/CppBlankProject/pull/4

I'm creating this ticket because it's been a little while and that PR hasn't received review. It's not really urgent for us to merge this, & I understand if you've been too busy to look at it, but I wanted to try a little harder to get it on your radar. Thanks.

**Comment by keunwoo** [comment]
Actually on further testing it looks like `cp` is not the only issue; the `sed` invocations are reliant on GNU sed too.

**Comment by francissauch** [comment]
Hello,
Sorry for the late reply.
I removed the -T option from cp so that the script works on MacOS.
I don't manage to reproduce the issue you are mentioning regarding the `sed` invocation though, do you have more context on that?

**Comment by alastairdglennie** [comment]
Hey keunwoo,
Further to what @francissauch said, I've opted to remove the worker_create.sh entirely given its flakiness. It's something that's susceptible to breaking from small changes to workers and isn't part of our automated testing. I'm currently in the process of rearchitecting this codebase to make the workers more self-contained and thus hopefully more easily manually copied to new projects (currently this also requires you to copy the root `dependencies` folder, copy the CMakeLists.txt inside the `schema` folder, and add the worker type to your relevant launch configurations).
If you're attempting to create new C++ workers and have any trouble then please do visit our forums at https://forums.improbable.io and we'll be happy to help!
Ally
